### ISSUE TITLE
Implicit frontend framework detection/configuration.

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-engine-nodejs#12]
Most other engines depend on the nodejs engine to provide a javascript asset compilation process if the application needs it. Currently, there are two issues with the implementation: 1) It's explicit and tedious for the other non-nodejs engines and 2) it assumes bower is the only package manager in existence.

Ideally, an engine would simply defer to nodejs for this setup in this way:

```bash

# install nodejs if the asset compilation requires
nodejs_prepare_asset_runtime

# configure the asset compilation environment
nodejs_configure_asset_environment

# optionally if the application doesn't have is own asset compilation process
nodejs_compile_assets

```

In this way, the engine can pick and choose which of the aforementioned steps will be required. In the case of rails, for example, the first `nodejs_prepare_asset_runtime` function will be the only requirement as rails handles the rest. For other engines, all of the steps might be necessary.

Following the aforementioned dsl, the details about which runtime (nodejs) and environment (bower, gulp, grunt, etc) are being used can be handled without the calling engine (python, ruby, rails, etc) having to be concerned about the details. Also, new runtimes and environments can be added without the calling engines needing to change.

**Comment by tylerflint** [comment]
@glinton @notxarb please review.

**Comment by notxarb** [comment]
What about lib_dirs to inject into the boxfile? We might want a nodejs_boxfile_asset_lib_dirs or something like that and that would return a list of dirs to add into the boxfile's lib_dirs?

**Comment by tylerflint** [comment]
I suppose I should elaborate what I was envisioning to happen at each of those phases. 

`nodejs_prepare_asset_runtime`

 Install nodejs, bower, gulp, etc.

`nodejs_configure_asset_environment `

 Bower install, etc

`nodejs_compile_assets `

 Would run gulp etc

**Comment by tylerflint** [comment]
@notxarb Great point! We will need that.
