### ISSUE TITLE
Please add a version for Node 8.1.4

### ISSUE THREAD

**Issue by benoneal** [nanobox-io/nanobox-engine-nodejs#22]
Or at least 7.10.1 

Especially in lieu of the recent announcement of the DoS vulnerability that has only been patched in specific versions.

**Comment by notxarb** [comment]
If you look in http://pkgsrc.nanobox.io/nanobox/base/Linux/ you'll see there's a package for nodejs-8.1.4
I'll have to make one for nodejs-7.10.1

**Comment by notxarb** [comment]
Nodejs-7.10.1 should be available now as well.
