### ISSUE TITLE
latest nodejs version (as default runtime) ?

### ISSUE THREAD

**Issue by boehm-s** [nanobox-io/nanobox-engine-nodejs#25]
Would it be possible to have a runtime named `nodejs-latest` and have it as default runtime ?

**Comment by sanderson** [comment]
With the way runtimes are loaded, this wouldn't work. Each runtime corresponds to a specific package in the [Nanobox pkgsrc](#), so `nodejs-latest` wouldn't match any packages.

When it comes to the default runtime, we try to stick to each language's recommended stable release. For Node.js, they [currently recommend `6.11`](https://nodejs.org/en/#home-intro) for most users. This is the current default of the `nodejs` engine.

Probably the easiest way to get the most recent version is to just list the major version in your `boxfile.yml`. Anytime a new minor version gets released, it'll pull that new version. And when a new major version is released, you'll just have to update the major version your `boxfile.yml`.

```yaml
run.config:
  engine: nodejs
  engine.config:
    runtime: nodejs-8
```
