### ISSUE TITLE
Node 4/5 support

### ISSUE THREAD

**Issue by kwhitaker** [nanobox-io/nanobox-engine-nodejs#4]
We like what you're doing with nanobox, but our project relies on newer versions of node.  Can we get that on the roadmap?

**Comment by sanderson** [comment]
@kwhitaker, I just updated the engine docs to inlcude `nodejs-4.2` in the version list. The package was available in the [nanobox pkgsrc](http://pkgsrc.nanobox.io/nanobox/base/Linux/), it just hadn't been added to the docs.

**Comment by kwhitaker** [comment]
@sanderson sweet! I'll take a look;  to get started, do I just specify that engine in my Boxfile after running `nanobox dev` for the first time?

**Comment by sanderson** [comment]
It should auto-detect your app as a nodejs app, but currently the engine defaults to nodejs-0.12 (we'll update that soon). While you *shouldn't* need to specify the engine, you will have to specify the runtime. Just to be safe, go ahead an specify both the engine and the version in your Boxfile:

```yaml
build:
  engine: nodejs
  runtime: nodejs-4.2
```

Changes to the Boxfile require a new deploy, which won't happen automatically while `nanobox dev` is running. You don't need to kill it. Just run: `nanobox deploy` to trigger a new deploy and apply the changes to your Boxfile.

Also, we've added nodejs-5 to our build "to-do" list. Hopefully we'll be able to update builds in the next couple of days.

**Comment by sanderson** [comment]
Sorry, update on the last comment. There's a known issue with specifying the engine that will cause it not work. And the `runtime` config has been changed to `nodejs_runtime`. I'll update the docs. So use this Boxfile:

```yaml
build:
  nodejs_runtime: nodejs-4.2
```

**Comment by sanderson** [comment]
Ok, I just updated the engine docs to correct the `runtime` specification and changed the default version to 4.2. The default version change won't apply until we publish new engine build images, but that should happen soon.

When the build images do get updated, I believe there's a daily check in the CLI that looks for a new version of the build images, but you can manually trigger it with the [update-images command](https://docs.nanobox.io/cli/update-images/):

```bash
nanobox update-images
```

**Comment by kwhitaker** [comment]
@sanderson so this is my Boxfile:

```
build:
  nodejs_runtime: nodejs-4.2
```

I ran `nanobox deploy` and then `nanobox dev`, and both give the following response before closing out:
```
+> Resuming nanobox...
   - Booting virtual machine....
+> Deploying codebase...
+> Cleaning containers
+> Creating build container
+> Detecting app language & engine
+> NO ENGINE DETECTED
   You're probably using a language we haven't built an engine for
   yet. Good news though, it's a quick and simple process to create
   an engine specific to your app or framework. Contact us so we can
   ask you a few questions about configuring and running your app
   and let's get this rolling!
   --------------------------------
   IRC   : #nanobox (freenode)
   EMAIL : engines@nanobox.io
   --------------------------------

! AN ERROR PREVENTED NANOBOX FROM BUILDING YOUR ENVIRONMENT !
- View the output above to diagnose the source of the problem
- You can also retry with --verbose for more detailed output

+> Suspending nanobox...
   - Saving virtual machine..
+> Exiting
```

I've also run `nanobox update-images`

**Comment by kwhitaker** [comment]
I deleted my the app for my repo in `~/.nanobox/apps`, and then attempted to do a fresh nanobox.  It threw an error while trying to import the base image. This is the log file:
```
2015-11-19 16:37:07 FATAL [commands/create] vagrant.Up() failed -  - exit status 1
2015-11-19 16:37:07 *LOG* Closing log now
```

**Comment by sanderson** [comment]
@kwhitaker, nodejs-5.0 and nodejs-5.1 are both now available as well. The documentation hasn't been updated yet, but it will be soon.
